dist: bionic
install:
  - sudo apt update && sudo apt install awscli zip wget -y
  - aws --version
  - wget https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip -O tf.zip && unzip tf.zip && sudo mv terraform /usr/bin/ && rm tf.zip
script:
  - terraform --version
  - exit 0